- [Exception과 Error의 차이](#exception과-error의-차이)
  - [Error](#error)
  - [Exception](#exception)
- [자바가 제공하는 예외 계층 구조](#자바가-제공하는-예외-계층-구조)
- [RuntimeException과 RE가 아닌 것의 차이](#runtimeexception과-re가-아닌-것의-차이)
  - [RuntimeException](#runtimeexception)
  - [RE가 아닌 것](#re가-아닌-것)
- [자바에서 예외 처리 방법](#자바에서-예외-처리-방법)
  - [예외 처리하기(try-catch)](#예외-처리하기try-catch)
    - [try-catch문에서의 흐름](#try-catch문에서의-흐름)
    - [catch블럭](#catch블럭)
    - [printStackTrace()와 getMessage()](#printstacktrace와-getmessage)
      - [printStackTrace()](#printstacktrace)
      - [getMessage()](#getmessage)
  - [예외 발생시키기(throw)](#예외-발생시키기throw)
  - [메서드에 예외 선언하기(throws)](#메서드에-예외-선언하기throws)
  - [finally블럭](#finally블럭)
- [사용자정의 예외 만들기](#사용자정의-예외-만들기)

---

# Exception과 Error의 차이

## Error

- 일단 발생하면 복구할 수 없는 심각한 오류
- 프로그램의 비정상적인 종료를 막을 길이 없다.

## Exception

- 발생하더라도 수습될 수 있는 비교적 덜 심각한 오류
- 발생하더라도 프로그래머가 이에 대한 적절한 코드를 미리 작성해 놓음으로써 프로그램의 비정상적인 종료를 막을 수 있다.

---

# 자바가 제공하는 예외 계층 구조

Object

- Throwable
  - Error
    - LinkageError
    - ThreadDeath
    - VirualMachineError
  - **Exception**
    - InterruptedException
    - InstantiationException
    - NoSuchMethodException
    - CloneNotFoundException
    - CloneNotSupportedException
    - IllegalAccessException
    - IOException
    - RuntimeException
      - ArithmeticException
      - ClassCastException
      - NullPointException
      - IndexOutOfBoundException

---

# RuntimeException과 RE가 아닌 것의 차이

## RuntimeException

- 주로 프로그래머의 실수에 의해서 발생

## RE가 아닌 것

- 주로 외부의 영향으로 발생
  - 프로그램 사용자의 동작에 의해 발생

---

# 자바에서 예외 처리 방법

## 예외 처리하기(try-catch)

- 정의
  - 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것
- 목적
  - 예외의 발생으로 인한 실행 중인 프로그램의 갑작스런 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있도록 만드는 것

```java
try {
//예외 발생 가능성이 있는 문장
} catch (Exception1 e1) {
//Exception1이 발생했을 경우, 처리하기 위한 문자
} catch (Exception2 e2) {
//Exception2이 발생했을 경우, 처리하기 위한 문자
}
```

- 발생한 예외의 종류와 일치하는 catch블럭이 없으면 예외는 처리되지 않는다.

### try-catch문에서의 흐름

- try블럭 내에서 예외가 발생한 경우
  - 발생한 예외와 일치하는 catch블럭이 있는지 확인한다.
  - 일치하는 catch블럭이 있으면 그 안의 문장들을 실행하고 전체 try-catch문을 빠져나간다.
- try블럭 내에서 예외가 발생하지 않은 경우
  - catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.
- **try블럭에서 예외가 발생하면, 예외가 발생한 위치 이후에 있는 try블럭의 문장들은 수행되지 않는다**
  - try블럭 내의 문장들의 순서 중요

### catch블럭

```java
catch(예외타입 참조변수){}
```

첫 번째 catch블럭부터 차례로 내려가면서 catch블럭의 괄호()내에 선언된 참조변수의 종류와 생성된 예외클래스의 인스턴스에 **instanceof연산자**를 이용해서 검사하게 된다.

- 검사결과가 true인 catch블럭을 만날 때까지 검사는 계속된다.

### printStackTrace()와 getMessage()

- 예외가 발생했을 때 *생성되는 예외 클래스의 인스턴스*에는 **발생한 예외에 대한 정보가 담겨 있다.**
- catch블럭의 괄호()에 선언된 **참조변수를 통해 이 인스턴스에 접근**할 수 있다.

#### printStackTrace()

- 예외발생 당시의 호출스택에 있었던 **메서드의 정보와 예외 메시지**를 화면에 출력

#### getMessage()

- 발생한 예외클래스의 **인스턴스에 저장된 메시지**를 얻을 수 있다.

## 예외 발생시키기(throw)

키워드 throw로 고의로 예외를 발생시킬 수 있다.

- 먼저, 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든다.
- throw를 이용해서 예외를 발생시킨다.

```java
Exception e = new Exception("여기는 에러메시지 적는 곳");
throw e;
//throw new Exception();
```


## 메서드에 예외 선언하기(throws)

메서드에 예외를 선언하려면, 메서드의 선언부에 키워드 throws를 사용해서 메서드 내에서 발생할 수 있는 예외를 적어준다.

- 예외가 여러 개일 경우 쉼표(,)로 구분한다.

```java
void method() throws Exception1, Exceoption2, ...{
  //메서드의 내용
}
```

메서드의 선언부에 예외를 선언

- 메서드를 사용하려는 사람이 메서드의 선언부를 봤을 때, 이 메서드를 사용하려면 어떠한 예외들이 처리되어야 하는지 쉽게 알 수 있다.
- 메서드를 작성할 때 메서드 내에서 발생할 가능성이 있는 예외를 선언부에 명시해 이 메서드를 사용하는 쪽에서는 이에 대한 처리를 하도록 강요하는 것(good~)

사실 메서드의 throws는 메서드에서 발생한 예외를 자신을 호출한 메서드에게 떠넘기는 것이다.

- 호출스택에 있는 메서드들을 따라 예외가 전달되다가 main메서드에서도 예외가 처리되지 않는다면, 프로그램 전체가 종료된다.

## finally블럭

finally 블럭은 예외의 발생여부에 상관없이 실행되어야할 코드를 포함시킬 목적으로 사용된다.

- 예외 발생한 경우
  - try -> catch -> finally
- 예외 발생하지 않은 경우
  - try -> finally

---

# 사용자정의 예외 만들기

기존의 정의된 예외 클래스 외에 필요에 따라 프로그래머가 새로운 예외 클래스를 정의할 수 있다.

- 가급적이면 새로운 예외 클래스를 만드릭보다 기존의 예외클래스를 활용하는게 좋다.

사용자정의 예외를 만드는 것은 Exception클래스나 RuntimeException클래스를 상속하여 만든다.

- 기존의 예외 클래스는 주로 Exception을 상속받아서 checked예외로 작성하는 경우가 많았지만, 요즘은 RuntimeException을 상속받아서 작성하는 쪼긍로 바뀌어가고 있다.
